language: php

dist: precise

php:
  - 7.3
  - 8.0
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script: make test